name: Workflow Triggered by Repository Dispatch

on:
  repository_dispatch:
    types:
      - workflow-trigger  # Use the same custom event name as in Repository A

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git
        env: 
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --global user.name "$GIT_USERNAME"
          git config --global user.email "$GIT_EMAIL"

      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add your workflow steps here
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach --recursive git fetch
          git submodule foreach --recursive git checkout origin/main

      - name: Create Symlink
        run: |
          ln -s "$(realpath azure-arc-docs/docs)" "azure-arc-jumpstart-app/public/symlink_documents"
          # Use the actual paths to your submodule and the symlink target

      # Rest of your workflow steps

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Final Steps
        run: |
          git add .
          git commit -m "updates"
          git push

      - name: Build App
        run:  |
          cd azure-arc-jumpstart-app
          npm install
          npm run build
          npm start
